// File automatically generated by fshasher

#include <utility>
#include <iterator>
#include <cstdint>
#include <cstddef>

extern const uint64_t Dlc1Hashes[];
extern const std::pair<const char *, uint32_t> Dlc1Files[];
extern const size_t Dlc1FilesSize;

const uint64_t Dlc1Hashes[] = {
    8527567923357035617ULL,
};

const std::pair<const char *, uint32_t> Dlc1Files[] = {
    { "player1p_00000000.big", 1 },
};

const size_t Dlc1FilesSize = std::size(Dlc1Files);
