// File automatically generated by fshasher

#include <utility>

extern const uint64_t Dlc2Hashes[];
extern const std::pair<const char *, uint32_t> Dlc2Files[];
extern const size_t Dlc2FilesSize;

const uint64_t Dlc2Hashes[] = {
    14670051145765016564ULL,
};

const std::pair<const char *, uint32_t> Dlc2Files[] = {
    { "presell_00000000.big", 1 },
};

const size_t Dlc2FilesSize = std::size(Dlc2Files);
