// File automatically generated by fshasher

#include <utility>
#include <iterator>
#include <cstdint>
#include <cstddef>

extern const uint64_t Dlc3Hashes[];
extern const std::pair<const char *, uint32_t> Dlc3Files[];
extern const size_t Dlc3FilesSize;

const uint64_t Dlc3Hashes[] = {
    14019480059828222351ULL,
    14148067306535790751ULL,
};

const std::pair<const char *, uint32_t> Dlc3Files[] = {
    { "dway_park_00000000.big", 1 },
    { "spa.bin", 1 },
};

const size_t Dlc3FilesSize = std::size(Dlc3Files);
