// File automatically generated by fshasher

#pragma once

#include <utility>
#include <cstdint>
#include <cstddef>

extern const uint64_t Dlc3Hashes[];
extern const std::pair<const char *, uint32_t> Dlc3Files[];
extern const size_t Dlc3FilesSize;

