// File automatically generated by fshasher

#include <utility>
#include <iterator>
#include <cstdint>
#include <cstddef>

extern const uint64_t Dlc4Hashes[];
extern const std::pair<const char *, uint32_t> Dlc4Files[];
extern const size_t Dlc4FilesSize;

const uint64_t Dlc4Hashes[] = {
    229511790874155570ULL,
    6409515604543890399ULL,
};

const std::pair<const char *, uint32_t> Dlc4Files[] = {
    { "maloof_money_cup_00000000.big", 1 },
    { "spa.bin", 1 },
};

const size_t Dlc4FilesSize = std::size(Dlc4Files);
