// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t Dlc4Hashes[];
extern const std::pair<const char *, uint32_t> Dlc4Files[];
extern const size_t Dlc4FilesSize;

