// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t Dlc5Hashes[];
extern const std::pair<const char *, uint32_t> Dlc5Files[];
extern const size_t Dlc5FilesSize;

