// File automatically generated by fshasher

#include <utility>
#include <iterator>
#include <cstdint>
#include <cstddef>

extern const uint64_t Dlc5Hashes[];
extern const std::pair<const char *, uint32_t> Dlc5Files[];
extern const size_t Dlc5FilesSize;

const uint64_t Dlc5Hashes[] = {
    2052549371290090503ULL,
    17188290333417776086ULL,
};

const std::pair<const char *, uint32_t> Dlc5Files[] = {
    { "play_00000000.big", 1 },
    { "spa.bin", 1 },
};

const size_t Dlc5FilesSize = std::size(Dlc5Files);
