// File automatically generated by fshasher

#pragma once

#include <utility>
#include <cstdint>
#include <cstddef>

extern const uint64_t Dlc7Hashes[];
extern const std::pair<const char *, uint32_t> Dlc7Files[];
extern const size_t Dlc7FilesSize;

