// File automatically generated by fshasher

#include <utility>
#include <iterator>
#include <cstdint>
#include <cstddef>

extern const uint64_t Dlc6Hashes[];
extern const std::pair<const char *, uint32_t> Dlc6Files[];
extern const size_t Dlc6FilesSize;

const uint64_t Dlc6Hashes[] = {
    276154106076234567ULL,
};

const std::pair<const char *, uint32_t> Dlc6Files[] = {
    { "project10_00000000.big", 1 },
};

const size_t Dlc6FilesSize = std::size(Dlc6Files);
