// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t Dlc6Hashes[];
extern const std::pair<const char *, uint32_t> Dlc6Files[];
extern const size_t Dlc6FilesSize;

