// File automatically generated by fshasher

#include <utility>

extern const uint64_t Dlc7Hashes[];
extern const std::pair<const char *, uint32_t> Dlc7Files[];
extern const size_t Dlc7FilesSize;

const uint64_t Dlc7Hashes[] = {
    7657000154894565560ULL,
};

const std::pair<const char *, uint32_t> Dlc7Files[] = {
    { "creator_00000000.big", 1 },
};

const size_t Dlc7FilesSize = std::size(Dlc7Files);
