// File automatically generated by fshasher

#include <utility>

extern const uint64_t Dlc8Hashes[];
extern const std::pair<const char *, uint32_t> Dlc8Files[];
extern const size_t Dlc8FilesSize;

const uint64_t Dlc8Hashes[] = {
    8843247274417199844ULL,
};

const std::pair<const char *, uint32_t> Dlc8Files[] = {
    { "unlockall_00000000.big", 1 },
};

const size_t Dlc8FilesSize = std::size(Dlc8Files);
