// File automatically generated by fshasher

#pragma once

#include <utility>

extern const uint64_t Dlc8Hashes[];
extern const std::pair<const char *, uint32_t> Dlc8Files[];
extern const size_t Dlc8FilesSize;

