// File automatically generated by fshasher

#include <utility>

extern const uint64_t UpdateHashes[];
extern const std::pair<const char *, uint32_t> UpdateFiles[];
extern const size_t UpdateFilesSize;

const uint64_t UpdateHashes[] = {
    7334510866062970864ULL,
};

const std::pair<const char *, uint32_t> UpdateFiles[] = {
    { "default.xexp", 1 },
};

const size_t UpdateFilesSize = std::size(UpdateFiles);
