// File automatically generated by fshasher

#include <utility>

extern const uint64_t UpdateHashes[];
extern const std::pair<const char *, uint32_t> UpdateFiles[];
extern const size_t UpdateFilesSize;

const uint64_t UpdateHashes[] = {
    5912062447025048551ULL,
    16254130348111888668ULL,
};

const std::pair<const char *, uint32_t> UpdateFiles[] = {
    { "data/webkit/EAWebkit.xexp", 1 },
    { "default.xexp", 1 },
};

const size_t UpdateFilesSize = std::size(UpdateFiles);
