[main]
file_path = "../skate-3/skate-3/default.xex"
patched_file_path = "../skate-3/default_patched.xex"
out_directory_path = "../out/default_ppc"
switch_table_file_path = "default_jump_table.toml"

restgprlr_14_address = 0x82f52130
savegprlr_14_address = 0x82f520e0
restfpr_14_address = 0x82f530ac
savefpr_14_address = 0x82f53060
restvmx_14_address = 0x82f570f8
savevmx_14_address = 0x82f56e60
restvmx_64_address = 0x82f5718c
savevmx_64_address = 0x82f56ef4

longjmp_address = 0x82f4feb0
setjmp_address = 0x82f6faa0

invalid_instructions = [
    { data = 0x82977d5c, size = 0xdc },
    { data = 0x82aeaf34, size = 0x48 },
    { data = 0x82954aa8, size = 0x60 },
    { data = 0x8250e45c, size = 0x34 },
    { data = 0x825443f8, size = 0x28 },
    { data = 0x82c9c1e0, size = 0x28 },
    { data = 0x82410dc0, size = 0x2c },
    { data = 0x824129c8, size = 0x28 },
    { data = 0x82413290, size = 0x2c },
    { data = 0x8266d690, size = 0x38 },
    { data = 0x8252581c, size = 0x34 },
    { data = 0x8294afc4, size = 0x3c },
    { data = 0x82714f3c, size = 0x28 },
    { data = 0x8294b268, size = 0x3c },
    { data = 0x8294f6b0, size = 0x3c },
    { data = 0x8294f8e8, size = 0x3c },
    { data = 0x8270fb44, size = 0x30 },
    { data = 0x82a51e00, size = 0x28 },
    { data = 0x82a51ed0, size = 0x28 },
    { data = 0x82a51fa0, size = 0x28 },
    { data = 0x825f1d78, size = 0x38 },
    { data = 0x8294fe2c, size = 0x40 },
    { data = 0x8275a69c, size = 0x3c },
    { data = 0x829500b4, size = 0x40 },
    { data = 0x8270b418, size = 0x7c },
    { data = 0x82e4a948, size = 0x48 },
    { data = 0x82aeb6e8, size = 0x48 },
    { data = 0x8270b9ac, size = 0x64 },
    { data = 0x82597aac, size = 0x34 },
    { data = 0x82a59b20, size = 0x28 },
    { data = 0x8272f6d4, size = 0x30 },
    { data = 0x82651f2c, size = 0x64 },
    { data = 0x82536cbc, size = 0x30 },
    { data = 0x82536d60, size = 0x30 },
    { data = 0x824e144c, size = 0x2c },
    { data = 0x824fcd10, size = 0xcc },
    { data = 0x829503e0, size = 0x3c },
    { data = 0x82950970, size = 0x40 },
    { data = 0x82950694, size = 0x3c },
    { data = 0x82dcb1e4, size = 0xc4 },
    { data = 0x82a79408, size = 0x48 },
    { data = 0x82950718, size = 0x3c },
    { data = 0x82c291b4, size = 0x4c },
    { data = 0x82432a84, size = 0x2c },
    { data = 0x82c75890, size = 0x40 },
    { data = 0x8262cb1c, size = 0x2c },
    { data = 0x826e19cc, size = 0x34 },
    { data = 0x82dcb3bc, size = 0x30 },
    { data = 0x8250200c, size = 0x3c },
    { data = 0x827073b8, size = 0x30 },
    { data = 0x8296a8dc, size = 0x84 },
    { data = 0x82952ab8, size = 0x40 },
    { data = 0x82921674, size = 0x50 },
    { data = 0x82952ba4, size = 0x40 },
    { data = 0x82e62610, size = 0x98 },
    { data = 0x82646b68, size = 0x64 },
    { data = 0x82995dac, size = 0x40 },
    { data = 0x82524b28, size = 0x30 },
    { data = 0x829244b8, size = 0x28 },
    { data = 0x82524588, size = 0x34 },
    { data = 0x827105ac, size = 0x30 },
    { data = 0x8295a578, size = 0x28 },
    { data = 0x82e61e18, size = 0xcc },
    { data = 0x825fece8, size = 0x3c },
    { data = 0x82919e2c, size = 0x98 },
    { data = 0x82dd4e94, size = 0x30 },
    { data = 0x824076dc, size = 0x2c },
    { data = 0x8263408c, size = 0x38 },
    { data = 0x82624ebc, size = 0x44 },
    { data = 0x824e18b0, size = 0x2c },
    { data = 0x82e8eaa0, size = 0xd0 },
    { data = 0x8240b720, size = 0x1b8 },
    { data = 0x826112c0, size = 0x3c },
    { data = 0x82aea040, size = 0x44 },
    { data = 0x8272d744, size = 0x4c },
    { data = 0x8279f228, size = 0x98 },
    { data = 0x82953778, size = 0x48 },
    { data = 0x82d9b6a0, size = 0x38 },
    { data = 0x824abdd4, size = 0x40 },
    { data = 0x826db054, size = 0x58 },
    { data = 0x824abe9c, size = 0x44 },
    { data = 0x82aa885c, size = 0x2c },
    { data = 0x8272d23c, size = 0x4c },
    { data = 0x827da78c, size = 0x30 },
    { data = 0x82924ae0, size = 0x3c },
    { data = 0x82783554, size = 0x68 },
    { data = 0x82eba824, size = 0x40 },
    { data = 0x82b11084, size = 0x18 },
    { data = 0x82aec518, size = 0x44 },
    { data = 0x82b11454, size = 0xe0 },
    { data = 0x827c9cec, size = 0x40 },
    { data = 0x824df3d0, size = 0x60 },
    { data = 0x82e78fec, size = 0x30 },
    { data = 0x824698f8, size = 0x34 },
    { data = 0x82a7dd78, size = 0x34 },
    { data = 0x82412c68, size = 0x28 },
    { data = 0x82ed2f60, size = 0x48 },
    { data = 0x826f9c38, size = 0xac },
    { data = 0x825391d8, size = 0x34 },
    { data = 0x828d21d0, size = 0x40 },
    { data = 0x82ead068, size = 0x38 },
    { data = 0x82a98a70, size = 0x2c },
    { data = 0x829672ac, size = 0x74 },
    { data = 0x826ee1e4, size = 0x3c },
    { data = 0x82435220, size = 0x50 },
    { data = 0x8270dcec, size = 0x84 },
    { data = 0x82a52ddc, size = 0x40 },
    { data = 0x829544d0, size = 0x70 },
    { data = 0x82507290, size = 0x2c },
    { data = 0x82b109e4, size = 0x54 },
    { data = 0x82d1b630, size = 0x28 },
    { data = 0x82923a94, size = 0x30 },
    { data = 0x8299593c, size = 0x2c },
    { data = 0x82e75458, size = 0x28 },
    { data = 0x824a6570, size = 0x28 },
    { data = 0x82622a64, size = 0x38 },
    { data = 0x82c78e5c, size = 0x30 },
    { data = 0x82d53168, size = 0x28 },
    { data = 0x825f03c0, size = 0xc4 },
    { data = 0x82612880, size = 0x34 },
    { data = 0x829a234c, size = 0x30 },
    { data = 0x82612068, size = 0x40 },
    { data = 0x82b682a8, size = 0xc0 },
    { data = 0x82e8ce90, size = 0x68 },
    { data = 0x82eb5d98, size = 0x40 },
    { data = 0x829cf3e0, size = 0x6c },
    { data = 0x82499600, size = 0x28 },
    { data = 0x82c7eab4, size = 0x2c },
    { data = 0x824ac150, size = 0x34 },
    { data = 0x8261ba30, size = 0x30 },
    { data = 0x825058a8, size = 0x34 },
    { data = 0x828ba00c, size = 0x40 },
    { data = 0x8250594c, size = 0x2c },
    { data = 0x824bcd38, size = 0x2c },
    { data = 0x8261bd24, size = 0xc4 },
    { data = 0x82823598, size = 0x38 },
    { data = 0x824aca64, size = 0x48 },
    { data = 0x82a5d814, size = 0x38 },
    { data = 0x829245a0, size = 0x30 },
    { data = 0x82a59350, size = 0x28 },
    { data = 0x824ab714, size = 0x10c },
    { data = 0x82476b24, size = 0x34 },
    { data = 0x82629064, size = 0x4c },
    { data = 0x8262d0b8, size = 0x2c },
    { data = 0x82e67914, size = 0x10c },
    { data = 0x826e88d0, size = 0xcc },
    { data = 0x82e58568, size = 0x50 },
    { data = 0x82ec67ac, size = 0x48 },
    { data = 0x82703188, size = 0x7c },
    { data = 0x82f29318, size = 0x3c },
    { data = 0x82e58960, size = 0x7c },
    { data = 0x825092f4, size = 0x40 },
    { data = 0x82b92d14, size = 0x2c },
    { data = 0x82497944, size = 0x4c },
    { data = 0x82915544, size = 0x90 },
    { data = 0x82dd163c, size = 0x8c },
    { data = 0x8249e6f0, size = 0x2c },
    { data = 0x82e593f4, size = 0x44 },
    { data = 0x82e504fc, size = 0x44 },
    { data = 0x82e5017c, size = 0x44 },
    { data = 0x82410b28, size = 0x2c },
    { data = 0x826e82a4, size = 0xb4 },
    { data = 0x825d2904, size = 0x38 },
    { data = 0x82712e88, size = 0x34 },
    { data = 0x8272a08c, size = 0x2c },
    { data = 0x82e513c4, size = 0x34 },
    { data = 0x82d1b3fc, size = 0x2c },
    { data = 0x82664f08, size = 0x40 },
    { data = 0x8271694c, size = 0x30 },
    { data = 0x82411210, size = 0x2c },
    { data = 0x82d531f4, size = 0x34 },
    { data = 0x825e5fb4, size = 0x44 },
    { data = 0x825f2830, size = 0x40 },
    { data = 0x82b73d18, size = 0x5c },
    { data = 0x82613b4c, size = 0x50 },
    { data = 0x826539a0, size = 0x34 },
    { data = 0x827115ec, size = 0x30 },
    { data = 0x82d2b818, size = 0x44 },
    { data = 0x8259eb3c, size = 0x3c },
    { data = 0x8291fed0, size = 0x68 },
    { data = 0x8291ff9c, size = 0x6c },
    { data = 0x82aac318, size = 0x2c },
    { data = 0x824114d8, size = 0x2c },
    { data = 0x82673cb4, size = 0x70 },
    { data = 0x82f2259c, size = 0x2c },
    { data = 0x829201c4, size = 0x3c },
    { data = 0x825089ac, size = 0x30 },
    { data = 0x82508ae8, size = 0x2c },
    { data = 0x82b123b0, size = 0x54 },
    { data = 0x82f053a4, size = 0x28 },
    { data = 0x8295a874, size = 0x28 },
    { data = 0x8295aafc, size = 0x28 },
    { data = 0x82f22b6c, size = 0xd4 },
    { data = 0x8248b360, size = 0x38 },
    { data = 0x8248b5e8, size = 0x68 },
    { data = 0x82469d5c, size = 0x34 },
    { data = 0x82d3fdf8, size = 0x30 },
    { data = 0x82612364, size = 0x40 },
    { data = 0x8250ff68, size = 0x38 },
    { data = 0x829cc9e4, size = 0x3c },
    { data = 0x829ccb04, size = 0x54 },
    { data = 0x82b63434, size = 0xc0 },
    { data = 0x829cccb8, size = 0x28 },
    { data = 0x829ccdd0, size = 0x2c },
    { data = 0x829ccf10, size = 0x28 },
    { data = 0x82dae2f4, size = 0x64 },
    { data = 0x829cd028, size = 0x48 },
    { data = 0x829cd0e4, size = 0x58 },
    { data = 0x8274bb54, size = 0xd8 },
    { data = 0x829cd318, size = 0x4c },
    { data = 0x829cd3c4, size = 0x50 },
    { data = 0x829cd510, size = 0x34 },
    { data = 0x8251ebe0, size = 0x3c },
    { data = 0x829cd6d4, size = 0x4c },
    { data = 0x8253d160, size = 0x34 },
    { data = 0x825258b8, size = 0x2c },
    { data = 0x829cd87c, size = 0x34 },
    { data = 0x829cd930, size = 0x4c },
    { data = 0x829cd9dc, size = 0x54 },
    { data = 0x829cdc74, size = 0x54 },
    { data = 0x82eaed18, size = 0x28 },
    { data = 0x828f868c, size = 0x54 },
    { data = 0x82a7d7fc, size = 0x34 },
    { data = 0x829966b8, size = 0x30 },
    { data = 0x82e5f850, size = 0x98 },
    { data = 0x8285ad08, size = 0x8c },
    { data = 0x82dca05c, size = 0x30 },
    { data = 0x829519e8, size = 0x3c },
    { data = 0x827157e4, size = 0x28 },
    { data = 0x8246a45c, size = 0x34 },
    { data = 0x82e4bf8c, size = 0x1b0 },
    { data = 0x826561f0, size = 0x28 },
    { data = 0x8271207c, size = 0x30 },
    { data = 0x82915900, size = 0x30 },
    { data = 0x82b0f7bc, size = 0x44 },
    { data = 0x82b0fb90, size = 0xe0 },
    { data = 0x82aecfac, size = 0x48 },
    { data = 0x82c839d4, size = 0x58 },
    { data = 0x82c83c78, size = 0x58 },
    { data = 0x82dd080c, size = 0x5c },
    { data = 0x82b62c50, size = 0x1a0 },
    { data = 0x829cfd9c, size = 0x6c },
    { data = 0x8270ad10, size = 0x34 },
    { data = 0x829d1dbc, size = 0x38 },
    { data = 0x829d1f20, size = 0x64 },
    { data = 0x829d1694, size = 0x3c },
    { data = 0x829d17c0, size = 0x30 },
    { data = 0x829d12c8, size = 0x3c },
    { data = 0x829d0ee0, size = 0x1d0 },
    { data = 0x829d1c2c, size = 0x5c },
    { data = 0x82b0ca38, size = 0x30 },
    { data = 0x829d19b0, size = 0x4c },
    { data = 0x824aaef0, size = 0x34 },
    { data = 0x824ab09c, size = 0xe8 },
    { data = 0x82a5287c, size = 0x40 },
    { data = 0x829d14f8, size = 0x28 },
    { data = 0x829d0868, size = 0x25c },
    { data = 0x82d0eeb4, size = 0xd4 },
    { data = 0x82a52220, size = 0x3c },
    { data = 0x829cff00, size = 0xcc },
    { data = 0x8273ac04, size = 0xc0 },
    { data = 0x82e4df14, size = 0x54 },
    { data = 0x8252593c, size = 0x30 },
    { data = 0x8296a54c, size = 0x28 },
    { data = 0x82b137e0, size = 0x38 },
    { data = 0x82b138a0, size = 0x2c },
    { data = 0x825ceb50, size = 0x38 },
    { data = 0x82a85c20, size = 0x3c },
    { data = 0x829cf8d0, size = 0x6c },
    { data = 0x825e3bc4, size = 0x28 },
    { data = 0x8264c644, size = 0x5c },
    { data = 0x828fd60c, size = 0x58 },
    { data = 0x8240f818, size = 0x154 },
    { data = 0x828fd910, size = 0x58 },
    { data = 0x829d20fc, size = 0x48 },
    { data = 0x829d26c0, size = 0x58 },
    { data = 0x829d2548, size = 0x94 },
    { data = 0x82612d20, size = 0xbc },
    { data = 0x82969a30, size = 0x94 },
    { data = 0x829d21e8, size = 0x30 },
    { data = 0x8259e940, size = 0x38 },
    { data = 0x825f0128, size = 0xbc },
    { data = 0x82499194, size = 0x28 },
    { data = 0x8249e26c, size = 0x38 },
    { data = 0x829810a0, size = 0x2c },
    { data = 0x8298120c, size = 0x28 },
    { data = 0x82981140, size = 0x38 },
    { data = 0x8250255c, size = 0x138 },
    { data = 0x8285b250, size = 0x8c },
    { data = 0x827aa2c0, size = 0x28 },
    { data = 0x82a7c824, size = 0x50 },
    { data = 0x82ea98bc, size = 0x44 },
    { data = 0x8259eddc, size = 0x40 },
    { data = 0x828f93a0, size = 0x54 },
    { data = 0x828f9db4, size = 0x3c },
    { data = 0x828f9e84, size = 0x3c },
    { data = 0x828fa6d4, size = 0x5c },
    { data = 0x828f99ac, size = 0x3c },
    { data = 0x8279eda8, size = 0x98 },
    { data = 0x82b6779c, size = 0x1a0 },
    { data = 0x828fae48, size = 0x64 },
    { data = 0x82407dd4, size = 0x1b8 },
    { data = 0x828fb0e0, size = 0x4c },
    { data = 0x828fab7c, size = 0x5c },
    { data = 0x828fa240, size = 0x64 },
    { data = 0x828fa510, size = 0x38 },
    { data = 0x8259e6d4, size = 0x34 },
    { data = 0x828f9854, size = 0x2c },
    { data = 0x828f9618, size = 0x2c },
    { data = 0x828f941c, size = 0x2c },
    { data = 0x828fa004, size = 0x2c },
    { data = 0x82e75978, size = 0x28 },
    { data = 0x82525794, size = 0x30 },
    { data = 0x82e5ed98, size = 0x9c },
    { data = 0x82952050, size = 0x40 },
    { data = 0x829522d4, size = 0x40 },
    { data = 0x829cfb8c, size = 0x6c },
    { data = 0x82c950bc, size = 0x3c },
    { data = 0x82e5e014, size = 0x34 },
    { data = 0x82ead9a4, size = 0x28 },
    { data = 0x8250d71c, size = 0x104 },
    { data = 0x82e07740, size = 0x60 },
    { data = 0x8251fc40, size = 0x3c },
    { data = 0x824a5378, size = 0x28 },
    { data = 0x8240de38, size = 0x154 },
    { data = 0x82e56904, size = 0x54 },
    { data = 0x828d0a74, size = 0x30 },
    { data = 0x82e56e74, size = 0x218 },
    { data = 0x823d99c4, size = 0x1b4 },
    { data = 0x82400fbc, size = 0xa0c },
    { data = 0x823d2a74, size = 0x1b4 },
    { data = 0x828b5adc, size = 0x48 },
    { data = 0x828b5824, size = 0x50 },
    { data = 0x824990cc, size = 0x2c },
    { data = 0x8250e728, size = 0x34 },
    { data = 0x82595d28, size = 0x28 },
    { data = 0x8270aadc, size = 0x38 },
    { data = 0x8272fa74, size = 0x38 },
    { data = 0x82a45bdc, size = 0x28 },
    { data = 0x82a45c84, size = 0x28 },
    { data = 0x82a45d5c, size = 0x28 },
    { data = 0x827db758, size = 0x28 },
    { data = 0x8296c42c, size = 0x84 }
]

functions = [
    { address = 0x828b5698, size = 0x538 },
    { address = 0x82498ec0, size = 0x288 },
    { address = 0x8250e410, size = 0x398 },
    { address = 0x82595b28, size = 0x480 },
    { address = 0x8270aa18, size = 0x110 },
    { address = 0x8272f8c0, size = 0x290 },
    { address = 0x82a45b40, size = 0x2d0 },
    { address = 0x827db6c0, size = 0x1F0 },
    { address = 0x8296c350, size = 0xb90 },
]