[main]
file_path = "../skate-3/skate-3/default.xex"
patched_file_path = "../skate-3/default_patched.xex"
out_directory_path = "../out/default_ppc"
switch_table_file_path = "default_jump_table.toml"

restgprlr_14_address = 0x82f52130
savegprlr_14_address = 0x82f520e0
restfpr_14_address = 0x82f530ac
savefpr_14_address = 0x82f53060
restvmx_14_address = 0x82f570f8
savevmx_14_address = 0x82f56e60
restvmx_64_address = 0x82f5718c
savevmx_64_address = 0x82f56ef4

longjmp_address = 0x82f4feb0
setjmp_address = 0x82f6faa0