[main]
file_path = "../skate-3/skate-3/data/webkit/EAWebkit.xex"
patched_file_path = "../skate-3/EAWebKit_patched.xex"
out_directory_path = "../out/eawebkit_ppc"
switch_table_file_path = "eawebkit_jump_table.toml"

restgprlr_14_address = 0x88476720
savegprlr_14_address = 0x884766d0
restfpr_14_address = 0x884771ec
savefpr_14_address = 0x884771a0
#restvmx_14_address =
#savevmx_14_address =
#restvmx_64_address =
#savevmx_64_address =

longjmp_address = 0x884789e0
setjmp_address = 0x88478d00